# MacBook Pro Touch Bar module parameters
# idle_timeout: -1 = display always on
# dim_timeout: -1 = never dim
# fnmode: 1 = Fn key switches F-keys/special-keys
options apple_ib_tb idle_timeout=-1 dim_timeout=-1 fnmode=1
